# docker-compose.yml
version: '3.7'
services:
  database:
    image: postgres
    volumes:
      - ./data-postgres:/data/postgres
    ports:
      - 127.0.0.1:5555:5432
    environment:
      POSTGRES_USER: quentin
      POSTGRES_PASSWORD: password_password
      POSTGRES_DB: local_trello
volumes:
  data-postgres:
